### ISSUE TITLE
正式リリースまでの準備

### ISSUE THREAD

**Issue by yuji38kwmt** [kurusugawa-computer/annofab-api-python-client#1]
* lintツールの実行結果を反映させる
* Makefileを書く
*

**Comment by yuji38kwmt** [comment]
testcodeは環境変数でなく`.netrc`から読み込むようにする

**Comment by yuji38kwmt** [comment]
readme.mdを修正

**Comment by exoego** [comment]
issue分けたほうが、どこまで終わってるか分かりますし、分担作業ができます

**Comment by yuji38kwmt** [comment]
以下の作業が完了したのでclose
* lintツールが成功するようにする
* makeコマンドが成功するようにする
