### ISSUE TITLE
Cannot run test if .netrc is missing

### ISSUE THREAD

**Issue by exoego** [kurusugawa-computer/annofab-api-python-client#25]
PR #24 introduces Travis, but Travis cannot run test due to this error.
https://travis-ci.com/kurusugawa-computer/annofab-api-python-client/builds/116225527#L201

I thinks tests should stub network and auth.
If tests involves network, it may fail if there are network issue even if code changes are OK.

**Comment by yuji38kwmt** [comment]
プルリクありがとうございます。

>I thinks tests should stub network and auth.
annofabapiのテストでは「AnnoFab本番環境から期待通りのレスポンスが返ってきてるか」を確認しているので、スタブは作らない予定です。

以下の対応方法を考えています。
* annofabapiのテスト用のユーザ、プロジェクトを作成
* travisの設定ファイルに、暗号化したuser_id, パスワードを記載する
https://qiita.com/hnw/items/39641e3643d480e9a0f1

**Comment by exoego** [comment]
テスト用のパスワードなどがパブリックなレポジトリに含まれるてると悪用のおそれがあります

**Comment by exoego** [comment]
AnnoFabがメンテナンスのときなどにテストが失敗します。
そのような外部依存の不安定なテストをPR検証時のテストに使うべきでないと思います

**Comment by yuji38kwmt** [comment]
>PR用には、ユニットテストやスタブを使ったインテグレーションテストくらいにとどめておくのがオススメです
分かりました。
ただ、今のannofabapiのテストは、ネットワークにアクセスするテストしかありません。
PR用のテストと、ネットワーク用のテストを分けるようにします。

**Comment by yuji38kwmt** [comment]
lintツールは実行できるようになりました。

**Comment by yuji38kwmt** [comment]
util系のメソッドをテストするようにしました。
